### ISSUE TITLE
[mobile] gray writing implies inactivity

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#114] opened 2017-12-08 10:04 UTC
problem:
the writing in the drop down menu on the right (' ... ') is gray for all inactive features and the active features are marked in black.
'x close' is also an active feature but shown in gray writing which implies inactivity

https://git.kolab.org/file/data/xg2kqhto5qhqqzb7jqqo/PHID-FILE-qhr45bpzkuzsbg64qw46/grafik.png

solution:
change colour of 'x close' to black

**Comment by alecpl** [comment] 2017-12-11 09:01
This is waiting for a designer. I though we may even change the header background color on phones. So, the text color would become white.

**Comment by alecpl** [comment] 2018-01-25 17:37
Duplicate of #113.

**Closed as completed by alecpl** 2018-01-25 17:37 UTC
Labels: Design
