### ISSUE TITLE
[mobile] strange design of the button named "Schließen" (=close) in the main menu

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#113] opened 2017-12-08 10:03 UTC
problem

the button  "Close" looks like it is not clickable (because it is gray)

https://git.kolab.org/file/data/jxaapcfhzsxy2ewjlghj/PHID-FILE-5cc3pg54j5zfrsdxo7po/24201038_1712068782200236_2141860615_o.png

**Comment by alecpl** [comment] 2017-12-08 14:37
Yes, I was waiting for a designer with that. That's anyway probably a duplicate of #108 and #97.

**Comment by alecpl** [comment] 2018-02-19 11:25
Fixed. Now the header has white text on dark background.

**Closed as completed by alecpl** 2018-02-19 11:25 UTC
Labels: bug, Design, UX, phone
