### ISSUE TITLE
 Logout button is partially covered by "browser information"

### ISSUE THREAD

**Issue by mbohlender** [roundcube/elastic#91] opened 2017-12-03 12:50 UTC
Logout buttons label can be partially covered by "browser information".

https://git.kolab.org/file/data/6kqqstebyk4tr6ckqz3j/PHID-FILE-57vunsnoml5oqhwzkfba/image.png

**Comment by alecpl** [comment] 2017-12-03 15:33
Duplicate of #78.

**Closed as completed by alecpl** 2017-12-03 15:33 UTC
